theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = false
cursorline = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
